server {
# Слушаем стандартный веб-порт (HTTP)
listen 80;
server_name localhost;

# Указываем, где лежат файлы фронтенда внутри контейнера
root /usr/share/nginx/html;
index index.html;

# Настройка роутинга
location / {
    try_files $uri $uri/ /index.html;
}

# Настройка кэширования статики (картинки, стили, скрипты) для ускорения загрузки
location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
    expires 30d;
    add_header Cache-Control "public, no-transform";
}


}